//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELearning.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class educationContainer : DbContext
    {
        public educationContainer()
            : base("name=educationContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<User> Users { get; set; }
        public DbSet<Subject> tbSubjects { get; set; }
        public DbSet<Lesson> tbLessons { get; set; }
        public DbSet<AssignedRole> tbAssignedRoles { get; set; }
        public DbSet<Exercise> tbExercises { get; set; }
        public DbSet<NewsFeedCategory> NewsFeedCategories { get; set; }
        public DbSet<NewsFeed> NewsFeeds { get; set; }
        public DbSet<Quiz> tbQuizs { get; set; }
        public DbSet<Section> Sections { get; set; }
        public DbSet<Subscriber> tbSubscribers { get; set; }
        public DbSet<SubscriberDetail> tbSubscriberDetails { get; set; }
        public DbSet<TrackUser> tbTrackUsers { get; set; }
    }
}
