//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELearning.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class educationEntities : DbContext
    {
        public educationEntities()
            : base("name=educationEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tbAssignRole> tbAssignRoles { get; set; }
        public DbSet<tbExercise> tbExercises { get; set; }
        public DbSet<tbLesson> tbLessons { get; set; }
        public DbSet<tbNewsFeed> tbNewsFeeds { get; set; }
        public DbSet<tbNewsFeedCategory> tbNewsFeedCategories { get; set; }
        public DbSet<tbQuiz> tbQuizs { get; set; }
        public DbSet<tbSection> tbSections { get; set; }
        public DbSet<tbSubject> tbSubjects { get; set; }
        public DbSet<tbSubscriber> tbSubscribers { get; set; }
        public DbSet<tbSubscriberDetail> tbSubscriberDetails { get; set; }
        public DbSet<tbTrackUser> tbTrackUsers { get; set; }
        public DbSet<tbUser> tbUsers { get; set; }
    }
}
