//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELearning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewsFeed
    {
        public NewsFeed()
        {
            this.SubscriberDetails = new HashSet<SubscriberDetail>();
        }
    
        public int NewsFeedID { get; set; }
        public int CategoryID { get; set; }
        public int Level { get; set; }
        public string Subject { get; set; }
        public string Topic { get; set; }
        public string Detail { get; set; }
        public string ContentFileName { get; set; }
        public System.DateTime Date { get; set; }
        public int UserID { get; set; }
    
        public virtual NewsFeedCategory NewsFeedCategory { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<SubscriberDetail> SubscriberDetails { get; set; }
    }
}
