//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELearning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewsFeedCategory
    {
        public NewsFeedCategory()
        {
            this.NewsFeeds = new HashSet<NewsFeed>();
        }
    
        public int CategoryID { get; set; }
        public string CategoryName { get; set; }
        public string Image { get; set; }
    
        public virtual ICollection<NewsFeed> NewsFeeds { get; set; }
    }
}
