//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELearning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subject
    {
        public Subject()
        {
            this.Lessons = new HashSet<Lesson>();
        }
    
        public int SubjectID { get; set; }
        public string SubjectName { get; set; }
        public Nullable<byte> Grade { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<Lesson> Lessons { get; set; }
    }
}
