//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELearning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbExercise
    {
        public int ExerciseID { get; set; }
        public string Exercise { get; set; }
        public string AnswerKey { get; set; }
        public Nullable<byte> Solution { get; set; }
        public Nullable<int> LessonID { get; set; }
    }
}
