//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELearning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbNewsFeed
    {
        public int NewsFeedID { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public Nullable<int> Level { get; set; }
        public string Subject { get; set; }
        public string Topic { get; set; }
        public string Detail { get; set; }
        public string ContentFileName { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> UserID { get; set; }
    }
}
