//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELearning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbSection
    {
        public int SectionID { get; set; }
        public string SectionName { get; set; }
        public Nullable<int> LessonID { get; set; }
        public Nullable<int> OrderNumber { get; set; }
        public string ContentFileName { get; set; }
    }
}
