//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELearning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbSubscriberDetail
    {
        public int SubscriberID { get; set; }
        public int NewsFeedID { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public string Description { get; set; }
    }
}
