//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELearning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbTrackUser
    {
        public int TrackUserID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> SectionID { get; set; }
        public string DataRecord { get; set; }
        public string ActivityType { get; set; }
    }
}
