//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELearning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrackUser
    {
        public int TrackUserID { get; set; }
        public int UserID { get; set; }
        public int SectionID { get; set; }
        public string DataRecord { get; set; }
        public string ActivityType { get; set; }
    
        public virtual User User { get; set; }
        public virtual Section Section { get; set; }
    }
}
